/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RozliczenieRouteImport } from './routes/rozliczenie'
import { Route as UczestnicyRouteImport } from './routes/uczestnicy'
import { Route as WyciagRouteImport } from './routes/wyciag'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiGoogleStartRouteImport } from './routes/api/google/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RozliczenieRoute = RozliczenieRouteImport.update({
  id: '/rozliczenie',
  path: '/rozliczenie',
  getParentRoute: () => rootRouteImport,
} as any)
const UczestnicyRoute = UczestnicyRouteImport.update({
  id: '/uczestnicy',
  path: '/uczestnicy',
  getParentRoute: () => rootRouteImport,
} as any)
const WyciagRoute = WyciagRouteImport.update({
  id: '/wyciag',
  path: '/wyciag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleStartRoute = ApiGoogleStartRouteImport.update({
  id: '/api/google/start',
  path: '/api/google/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rozliczenie': typeof RozliczenieRoute
  '/uczestnicy': typeof UczestnicyRoute
  '/wyciag': typeof WyciagRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/start': typeof ApiGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rozliczenie': typeof RozliczenieRoute
  '/uczestnicy': typeof UczestnicyRoute
  '/wyciag': typeof WyciagRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/start': typeof ApiGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rozliczenie': typeof RozliczenieRoute
  '/uczestnicy': typeof UczestnicyRoute
  '/wyciag': typeof WyciagRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/start': typeof ApiGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rozliczenie'
    | '/uczestnicy'
    | '/wyciag'
    | '/api/google/callback'
    | '/api/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rozliczenie'
    | '/uczestnicy'
    | '/wyciag'
    | '/api/google/callback'
    | '/api/google/start'
  id:
    | '__root__'
    | '/'
    | '/rozliczenie'
    | '/uczestnicy'
    | '/wyciag'
    | '/api/google/callback'
    | '/api/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RozliczenieRoute: typeof RozliczenieRoute
  UczestnicyRoute: typeof UczestnicyRoute
  WyciagRoute: typeof WyciagRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiGoogleStartRoute: typeof ApiGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rozliczenie': {
      id: '/rozliczenie'
      path: '/rozliczenie'
      fullPath: '/rozliczenie'
      preLoaderRoute: typeof RozliczenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uczestnicy': {
      id: '/uczestnicy'
      path: '/uczestnicy'
      fullPath: '/uczestnicy'
      preLoaderRoute: typeof UczestnicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wyciag': {
      id: '/wyciag'
      path: '/wyciag'
      fullPath: '/wyciag'
      preLoaderRoute: typeof WyciagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/start': {
      id: '/api/google/start'
      path: '/api/google/start'
      fullPath: '/api/google/start'
      preLoaderRoute: typeof ApiGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RozliczenieRoute: RozliczenieRoute,
  UczestnicyRoute: UczestnicyRoute,
  WyciagRoute: WyciagRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiGoogleStartRoute: ApiGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
