/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RozliczenieRouteImport } from './routes/rozliczenie'
import { Route as UczestnicyRouteImport } from './routes/uczestnicy'
import { Route as WyciagRouteImport } from './routes/wyciag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RozliczenieRoute = RozliczenieRouteImport.update({
  id: '/rozliczenie',
  path: '/rozliczenie',
  getParentRoute: () => rootRouteImport,
} as any)
const UczestnicyRoute = UczestnicyRouteImport.update({
  id: '/uczestnicy',
  path: '/uczestnicy',
  getParentRoute: () => rootRouteImport,
} as any)
const WyciagRoute = WyciagRouteImport.update({
  id: '/wyciag',
  path: '/wyciag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rozliczenie': typeof RozliczenieRoute
  '/uczestnicy': typeof UczestnicyRoute
  '/wyciag': typeof WyciagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rozliczenie': typeof RozliczenieRoute
  '/uczestnicy': typeof UczestnicyRoute
  '/wyciag': typeof WyciagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rozliczenie': typeof RozliczenieRoute
  '/uczestnicy': typeof UczestnicyRoute
  '/wyciag': typeof WyciagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rozliczenie' | '/uczestnicy' | '/wyciag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rozliczenie' | '/uczestnicy' | '/wyciag'
  id: '__root__' | '/' | '/rozliczenie' | '/uczestnicy' | '/wyciag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RozliczenieRoute: typeof RozliczenieRoute
  UczestnicyRoute: typeof UczestnicyRoute
  WyciagRoute: typeof WyciagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rozliczenie': {
      id: '/rozliczenie'
      path: '/rozliczenie'
      fullPath: '/rozliczenie'
      preLoaderRoute: typeof RozliczenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uczestnicy': {
      id: '/uczestnicy'
      path: '/uczestnicy'
      fullPath: '/uczestnicy'
      preLoaderRoute: typeof UczestnicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wyciag': {
      id: '/wyciag'
      path: '/wyciag'
      fullPath: '/wyciag'
      preLoaderRoute: typeof WyciagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RozliczenieRoute: RozliczenieRoute,
  UczestnicyRoute: UczestnicyRoute,
  WyciagRoute: WyciagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
